/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CollectorsRouteImport } from './routes/collectors'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTasksRouteImport } from './routes/dashboard/tasks'
import { Route as DashboardSubmissionsRouteImport } from './routes/dashboard/submissions'
import { Route as DashboardCollectorsRouteImport } from './routes/dashboard/collectors'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorsRoute = CollectorsRouteImport.update({
  id: '/collectors',
  path: '/collectors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubmissionsRoute = DashboardSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCollectorsRoute = DashboardCollectorsRouteImport.update({
  id: '/collectors',
  path: '/collectors',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collectors': typeof CollectorsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/dashboard/collectors': typeof DashboardCollectorsRoute
  '/dashboard/submissions': typeof DashboardSubmissionsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collectors': typeof CollectorsRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/dashboard/collectors': typeof DashboardCollectorsRoute
  '/dashboard/submissions': typeof DashboardSubmissionsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collectors': typeof CollectorsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/dashboard/collectors': typeof DashboardCollectorsRoute
  '/dashboard/submissions': typeof DashboardSubmissionsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collectors'
    | '/dashboard'
    | '/login'
    | '/overview'
    | '/reports'
    | '/review'
    | '/settings'
    | '/tasks'
    | '/dashboard/collectors'
    | '/dashboard/submissions'
    | '/dashboard/tasks'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collectors'
    | '/login'
    | '/overview'
    | '/reports'
    | '/review'
    | '/settings'
    | '/tasks'
    | '/dashboard/collectors'
    | '/dashboard/submissions'
    | '/dashboard/tasks'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/collectors'
    | '/dashboard'
    | '/login'
    | '/overview'
    | '/reports'
    | '/review'
    | '/settings'
    | '/tasks'
    | '/dashboard/collectors'
    | '/dashboard/submissions'
    | '/dashboard/tasks'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectorsRoute: typeof CollectorsRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  OverviewRoute: typeof OverviewRoute
  ReportsRoute: typeof ReportsRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collectors': {
      id: '/collectors'
      path: '/collectors'
      fullPath: '/collectors'
      preLoaderRoute: typeof CollectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tasks': {
      id: '/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/submissions': {
      id: '/dashboard/submissions'
      path: '/submissions'
      fullPath: '/dashboard/submissions'
      preLoaderRoute: typeof DashboardSubmissionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/collectors': {
      id: '/dashboard/collectors'
      path: '/collectors'
      fullPath: '/dashboard/collectors'
      preLoaderRoute: typeof DashboardCollectorsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCollectorsRoute: typeof DashboardCollectorsRoute
  DashboardSubmissionsRoute: typeof DashboardSubmissionsRoute
  DashboardTasksRoute: typeof DashboardTasksRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCollectorsRoute: DashboardCollectorsRoute,
  DashboardSubmissionsRoute: DashboardSubmissionsRoute,
  DashboardTasksRoute: DashboardTasksRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectorsRoute: CollectorsRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  OverviewRoute: OverviewRoute,
  ReportsRoute: ReportsRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
