// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-collectors.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod";

// src/lib/mock-data.ts
var PRIORITIES = ["low", "medium", "high", "urgent"];
var ZONES = ["North", "South", "East", "West", "Central"];
var COLLECTOR_STATUSES = ["active", "inactive", "suspended", "pending"];
var NOW = "2026-07-13 12:00";
var collectors = [
  { id: "C-101", name: "Ravi Kumar", phone: "+919845012034", zone: "North", status: "active", collectorType: "Individual", preferredLanguage: "Kannada", registeredAt: "2025-11-02 09:00", lastActiveAt: "2026-07-13 08:10" },
  { id: "C-102", name: "Anita Sharma", phone: "+919886023112", zone: "South", status: "active", collectorType: "Individual", preferredLanguage: "Hindi", registeredAt: "2025-11-10 09:00", lastActiveAt: "2026-07-12 19:40" },
  { id: "C-103", name: "Mohammed Irfan", phone: "+919901255461", zone: "East", status: "active", collectorType: "NGO Affiliated", organization: "CleanBLR Trust", preferredLanguage: "Urdu", registeredAt: "2025-12-01 09:00", lastActiveAt: "2026-07-12 18:20" },
  { id: "C-104", name: "Sunita Patil", phone: "+919822188720", zone: "West", status: "inactive", collectorType: "Individual", preferredLanguage: "Kannada", registeredAt: "2025-10-14 09:00", lastActiveAt: "2026-07-05 10:00" },
  { id: "C-105", name: "Deepak Yadav", phone: "+919740133298", zone: "Central", status: "active", collectorType: "Contractor", organization: "Yadav Waste Services", preferredLanguage: "Hindi", registeredAt: "2025-09-20 09:00", lastActiveAt: "2026-07-13 11:05" },
  { id: "C-106", name: "Priya Menon", phone: "+919847091123", zone: "South", status: "active", collectorType: "Municipal Staff", organization: "BBMP Ward 155", preferredLanguage: "English", registeredAt: "2025-12-15 09:00", lastActiveAt: "2026-07-12 12:20" },
  { id: "C-107", name: "Arjun Reddy", phone: "+919632042200", zone: "East", status: "suspended", collectorType: "Individual", preferredLanguage: "Telugu", registeredAt: "2025-11-28 09:00", lastActiveAt: "2026-07-09 11:00", internalNotes: "Suspended after repeated missed pickups \u2014 pending review." },
  { id: "C-108", name: "Kavita Joshi", phone: "+919819177340", zone: "North", status: "active", collectorType: "Individual", preferredLanguage: "Kannada", registeredAt: "2026-01-05 09:00", lastActiveAt: "2026-07-13 09:35" },
  { id: "C-109", name: "Farhan Sheikh", phone: "+919008044210", zone: "East", status: "pending", preferredLanguage: "Urdu", registeredAt: "2026-07-12 10:00", lastActiveAt: "\u2014" },
  { id: "C-110", name: "Meera Nair", phone: "+919021066531", zone: "South", status: "pending", preferredLanguage: "Tamil", registeredAt: "2026-07-13 08:00", lastActiveAt: "\u2014" }
];
var tasksBase = [
  { id: "T-2041", title: "Garbage overflow near bus stand", description: "Overflowing municipal bin attracting stray animals near the bus stand.", location: "MG Road, Ward 12", latitude: 12.9756, longitude: 77.6068, zone: "Central", status: "submitted", priority: "high", hotspotType: "Mixed waste", assignee: "Deepak Yadav", createdBy: "Ananya Rao", createdAt: "2026-07-11 09:14", dueAt: "2026-07-13 18:00", wasteType: "Mixed Municipal", estimatedWasteKg: 180, instructions: "Coordinate with the bus stand supervisor before starting.", hasReferencePhoto: true },
  { id: "T-2042", title: "Illegal dumping cleanup", description: "Construction waste dumped overnight on the industrial access road.", location: "Yeshwanthpur Industrial Area", latitude: 13.0284, longitude: 77.5407, zone: "North", status: "in_progress", priority: "urgent", hotspotType: "Illegal dumping", assignee: "Ravi Kumar", createdBy: "Ananya Rao", createdAt: "2026-07-12 07:22", dueAt: "2026-07-13 12:00", wasteType: "Construction Debris", estimatedWasteKg: 620, instructions: "Requires a truck for debris removal; contact depot for scheduling." },
  { id: "T-2043", title: "Clogged storm drain", description: "Storm drain blocked with plastic and silt, causing waterlogging after rain.", location: "Koramangala 5th Block", latitude: 12.9346, longitude: 77.6146, zone: "South", status: "assigned", priority: "medium", hotspotType: "Drainage or canal waste", assignee: "Anita Sharma", createdBy: "Ananya Rao", createdAt: "2026-07-12 10:03", dueAt: "2026-07-14 17:00", wasteType: "Mixed Municipal", estimatedWasteKg: 95 },
  { id: "T-2044", title: "Construction debris removal", description: "Leftover rubble from a nearby renovation blocking the footpath.", location: "Whitefield Main Road", latitude: 12.9698, longitude: 77.75, zone: "East", status: "open", priority: "medium", hotspotType: "Construction debris", createdBy: "Ananya Rao", createdAt: "2026-07-12 11:41", dueAt: "2026-07-15 12:00", wasteType: "Construction Debris", estimatedWasteKg: 340 },
  { id: "T-2045", title: "Market waste pile-up", description: "Vegetable and organic waste piling up between market stalls.", location: "KR Market, Stall Row 4", latitude: 12.9634, longitude: 77.5785, zone: "Central", status: "submitted", priority: "high", hotspotType: "Market waste", assignee: "Deepak Yadav", createdBy: "Ananya Rao", createdAt: "2026-07-11 18:32", dueAt: "2026-07-13 09:00", wasteType: "Organic", estimatedWasteKg: 210, instructions: "Coordinate with stall owners for early-morning access." },
  { id: "T-2046", title: "Plastic dump near lake", description: "Plastic bottles and packaging washed up along the lake bund.", location: "Bellandur Lake, East Bund", latitude: 12.926, longitude: 77.6762, zone: "East", status: "rejected", priority: "high", hotspotType: "Plastic litter", assignee: "Mohammed Irfan", createdBy: "Ananya Rao", createdAt: "2026-07-10 14:00", dueAt: "2026-07-12 18:00", wasteType: "Plastic", estimatedWasteKg: 150, internalNotes: "Second attempt needed \u2014 resubmission requested after unclear photos." },
  { id: "T-2047", title: "School premises cleanup", description: "General cleanup of the school compound ahead of the term restart.", location: "Govt. School, Rajajinagar", latitude: 12.9915, longitude: 77.554, zone: "West", status: "approved", priority: "low", hotspotType: "Mixed waste", assignee: "Sunita Patil", createdBy: "Ananya Rao", createdAt: "2026-07-09 08:15", dueAt: "2026-07-11 17:00", wasteType: "Mixed Municipal", estimatedWasteKg: 60 },
  { id: "T-2048", title: "Temple street sweep", description: "Flower and food waste accumulation after the weekend festival.", location: "Malleshwaram 8th Cross", latitude: 13.0067, longitude: 77.573, zone: "North", status: "in_progress", priority: "low", hotspotType: "Mixed waste", assignee: "Kavita Joshi", createdBy: "Ananya Rao", createdAt: "2026-07-12 06:40", dueAt: "2026-07-14 12:00", wasteType: "Mixed Municipal", estimatedWasteKg: 40 },
  { id: "T-2049", title: "Sewage overflow report", description: "Manhole overflow reported by residents, needs urgent attention.", location: "HSR Layout Sector 2", latitude: 12.9121, longitude: 77.6446, zone: "South", status: "assigned", priority: "urgent", hotspotType: "Drainage or canal waste", assignee: "Priya Menon", createdBy: "Ananya Rao", createdAt: "2026-07-12 12:20", dueAt: "2026-07-13 20:00", wasteType: "Sewage/Sludge", estimatedWasteKg: 500, instructions: "Coordinate with the water board before entering the manhole area." },
  { id: "T-2050", title: "Roadside garbage bin damaged", description: "Damaged bin spilling waste onto the footpath.", location: "Indiranagar 100ft Road", latitude: 12.9719, longitude: 77.6412, zone: "East", status: "open", priority: "low", hotspotType: "Mixed waste", createdBy: "Ananya Rao", createdAt: "2026-07-12 13:00", dueAt: "2026-07-16 12:00", wasteType: "Mixed Municipal", estimatedWasteKg: 25 },
  { id: "T-2051", title: "Public toilet cleanup", description: "Deep cleaning requested for the public toilet block at the bus terminal.", location: "Majestic Bus Terminal", latitude: 12.9767, longitude: 77.5713, zone: "Central", status: "canceled", priority: "medium", hotspotType: "Other", createdBy: "Ananya Rao", createdAt: "2026-07-10 09:00", dueAt: "2026-07-12 18:00", wasteType: "Sewage/Sludge", estimatedWasteKg: 80, internalNotes: "Canceled \u2014 contractor handled this directly." },
  { id: "T-2052", title: "Riverside plastic cleanup", description: "Plastic waste collecting along the lake bund after recent rains.", location: "Hebbal Lake Bund", latitude: 13.0453, longitude: 77.595, zone: "North", status: "accepted", priority: "high", hotspotType: "Plastic litter", assignee: "Ravi Kumar", createdBy: "Ananya Rao", createdAt: "2026-07-07 09:00", dueAt: "2026-07-14 12:00", wasteType: "Plastic", estimatedWasteKg: 300 },
  { id: "T-2053", title: "Park litter collection", description: "Weekend litter buildup around the walking track and play area.", location: "Sankey Tank Park", latitude: 13.0067, longitude: 77.573, zone: "North", status: "accepted", priority: "medium", hotspotType: "Mixed waste", assignee: "Kavita Joshi", createdBy: "Ananya Rao", createdAt: "2026-07-08 10:00", dueAt: "2026-07-15 12:00", wasteType: "Mixed Municipal", estimatedWasteKg: 70 },
  { id: "T-2054", title: "E-waste pickup request", description: "Decommissioned office electronics awaiting scheduled pickup.", location: "Whitefield Tech Park", latitude: 12.9698, longitude: 77.75, zone: "East", status: "declined", priority: "medium", hotspotType: "Other", assignee: "Arjun Reddy", createdBy: "Ananya Rao", createdAt: "2026-07-09 11:00", dueAt: "2026-07-16 12:00", wasteType: "E-Waste", estimatedWasteKg: 120, internalNotes: "Collector declined \u2014 requires specialized handling, reassignment pending." },
  { id: "T-2055", title: "Community hall cleanup", description: "Post-event cleanup for the community hall and adjoining grounds.", location: "Jayanagar 4th Block", latitude: 12.9254, longitude: 77.5931, zone: "South", status: "assigned", priority: "low", hotspotType: "Organic waste", assignee: "Priya Menon", createdBy: "Ananya Rao", createdAt: "2026-07-10 09:30", dueAt: "2026-07-17 12:00", wasteType: "Organic", estimatedWasteKg: 50 },
  { id: "T-2056", title: "Lakeside debris clearance", description: "Construction rubble dumped near the lake walking path.", location: "Madiwala Lake", latitude: 12.9187, longitude: 77.6144, zone: "South", status: "in_progress", priority: "medium", hotspotType: "Construction debris", assignee: "Anita Sharma", createdBy: "Ananya Rao", createdAt: "2026-07-11 08:00", dueAt: "2026-07-14 12:00", wasteType: "Construction Debris", estimatedWasteKg: 400 },
  { id: "T-2057", title: "Industrial estate cleanup", description: "Scrap and debris accumulation along the estate's internal road.", location: "Peenya Industrial Area", latitude: 13.0284, longitude: 77.5407, zone: "East", status: "submitted", priority: "high", hotspotType: "Construction debris", assignee: "Mohammed Irfan", createdBy: "Ananya Rao", createdAt: "2026-07-10 07:00", dueAt: "2026-07-12 20:00", wasteType: "Construction Debris", estimatedWasteKg: 550, hasReferencePhoto: true },
  { id: "T-2058", title: "Highway shoulder cleanup", description: "Litter and debris along the service lane shoulder.", location: "Tumkur Road Service Lane", latitude: 13.045, longitude: 77.522, zone: "North", status: "approved", priority: "medium", hotspotType: "Mixed waste", assignee: "Ravi Kumar", createdBy: "Ananya Rao", createdAt: "2026-07-07 08:00", dueAt: "2026-07-09 17:00", wasteType: "Mixed Municipal", estimatedWasteKg: 210 },
  { id: "T-2059", title: "Ward 5 plastic removal", description: "Plastic waste segregation and removal drive for Ward 5.", location: "Shivajinagar Ward 5", latitude: 12.9857, longitude: 77.6057, zone: "Central", status: "approved", priority: "high", hotspotType: "Plastic litter", assignee: "Deepak Yadav", createdBy: "Ananya Rao", createdAt: "2026-07-08 09:00", dueAt: "2026-07-10 17:00", wasteType: "Plastic", estimatedWasteKg: 260 },
  { id: "T-2060", title: "Canal desilting support", description: "Silt and solid waste removal along a 40m canal stretch.", location: "Vrishabhavathi Canal", latitude: 12.955, longitude: 77.522, zone: "Central", status: "approved", priority: "medium", hotspotType: "Drainage or canal waste", assignee: "Deepak Yadav", createdBy: "Ananya Rao", createdAt: "2026-07-09 10:00", dueAt: "2026-07-11 17:00", wasteType: "Sewage/Sludge", estimatedWasteKg: 700 },
  { id: "T-2061", title: "Community park cleanup", description: "Leaf litter and organic waste cleanup ahead of the weekend event.", location: "Ejipura Park", latitude: 12.9401, longitude: 77.6357, zone: "South", status: "approved", priority: "low", hotspotType: "Organic waste", assignee: "Anita Sharma", createdBy: "Ananya Rao", createdAt: "2026-07-11 09:00", dueAt: "2026-07-13 17:00", wasteType: "Organic", estimatedWasteKg: 90 },
  { id: "T-2062", title: "Railway underpass cleanup", description: "Waste clearance ahead of the evening commute at the underpass.", location: "Yeshwanthpur Underpass", latitude: 13.0284, longitude: 77.5407, zone: "North", status: "approved", priority: "high", hotspotType: "Mixed waste", assignee: "Kavita Joshi", createdBy: "Ananya Rao", createdAt: "2026-07-13 08:00", dueAt: "2026-07-13 17:00", wasteType: "Mixed Municipal", estimatedWasteKg: 150 }
];
var submissions = [
  { id: "S-511", taskId: "T-2041", taskTitle: "Garbage overflow near bus stand", collector: "Deepak Yadav", zone: "Central", priority: "high", wasteType: "Mixed Municipal", quantityKg: 180, submittedAt: "2026-07-12 16:22", status: "pending", note: "Cleared 3 bins, photos attached.", latitude: 12.9758, longitude: 77.607, hasBeforePhoto: true, hasAfterPhoto: true },
  { id: "S-512", taskId: "T-2045", taskTitle: "Market waste pile-up", collector: "Deepak Yadav", zone: "Central", priority: "high", wasteType: "Organic", quantityKg: 210, submittedAt: "2026-07-12 17:04", status: "pending", note: "Stall row 4 cleared.", latitude: 12.982, longitude: 77.594, hasBeforePhoto: false, hasAfterPhoto: true },
  { id: "S-513", taskId: "T-2046", taskTitle: "Plastic dump near lake", collector: "Mohammed Irfan", zone: "East", priority: "high", wasteType: "Plastic", quantityKg: 150, submittedAt: "2026-07-11 15:40", decidedAt: "2026-07-11 16:00", status: "rejected", note: "Photos unclear, revisit needed.", latitude: 12.9263, longitude: 77.6758, hasBeforePhoto: true, hasAfterPhoto: true, reviewer: "Ananya Rao", rejectionReason: "Photos unclear" },
  { id: "S-514", taskId: "T-2047", taskTitle: "School premises cleanup", collector: "Sunita Patil", zone: "West", priority: "low", wasteType: "Mixed Municipal", quantityKg: 60, submittedAt: "2026-07-10 12:11", decidedAt: "2026-07-11 09:00", status: "approved", note: "Verified by ward officer.", latitude: 12.9913, longitude: 77.5543, hasBeforePhoto: true, hasAfterPhoto: true, reviewer: "Ananya Rao" },
  { id: "S-515", taskId: "T-2057", taskTitle: "Industrial estate cleanup", collector: "Mohammed Irfan", zone: "East", priority: "high", wasteType: "Construction Debris", quantityKg: 550, submittedAt: "2026-07-12 18:00", status: "pending", note: "Debris bagged, awaiting truck pickup confirmation.", latitude: 13.0281, longitude: 77.541, hasBeforePhoto: true, hasAfterPhoto: true },
  { id: "S-516", taskId: "T-2058", taskTitle: "Highway shoulder cleanup", collector: "Ravi Kumar", zone: "North", priority: "medium", wasteType: "Mixed Municipal", quantityKg: 210, submittedAt: "2026-07-08 17:00", decidedAt: "2026-07-09 10:00", status: "approved", note: "Shoulder cleared both directions.", latitude: 13.0452, longitude: 77.5223, hasBeforePhoto: true, hasAfterPhoto: true, reviewer: "Ananya Rao" },
  { id: "S-517", taskId: "T-2059", taskTitle: "Ward 5 plastic removal", collector: "Deepak Yadav", zone: "Central", priority: "high", wasteType: "Plastic", quantityKg: 260, submittedAt: "2026-07-09 16:00", decidedAt: "2026-07-10 09:00", status: "approved", note: "Segregated for recycling pickup.", latitude: 12.986, longitude: 77.606, hasBeforePhoto: true, hasAfterPhoto: true, reviewer: "Ananya Rao" },
  { id: "S-518", taskId: "T-2060", taskTitle: "Canal desilting support", collector: "Deepak Yadav", zone: "Central", priority: "medium", wasteType: "Sewage/Sludge", quantityKg: 700, submittedAt: "2026-07-10 17:30", decidedAt: "2026-07-11 11:00", status: "approved", note: "Desilted 40m stretch, verified by engineer.", latitude: 12.9553, longitude: 77.5223, hasBeforePhoto: true, hasAfterPhoto: true, reviewer: "Ananya Rao" },
  { id: "S-519", taskId: "T-2061", taskTitle: "Community park cleanup", collector: "Anita Sharma", zone: "South", priority: "low", wasteType: "Organic", quantityKg: 90, submittedAt: "2026-07-12 15:00", decidedAt: "2026-07-12 18:00", status: "approved", note: "Leaf litter and organic waste composted on-site.", latitude: 12.9403, longitude: 77.6359, hasBeforePhoto: true, hasAfterPhoto: true, reviewer: "Ananya Rao" },
  { id: "S-520", taskId: "T-2062", taskTitle: "Railway underpass cleanup", collector: "Kavita Joshi", zone: "North", priority: "high", wasteType: "Mixed Municipal", quantityKg: 150, submittedAt: "2026-07-13 09:30", decidedAt: "2026-07-13 11:00", status: "approved", note: "Underpass cleared before evening commute.", latitude: 13.0286, longitude: 77.5409, hasBeforePhoto: true, hasAfterPhoto: true, reviewer: "Ananya Rao" }
];
function toTimestamp(dateStr) {
  return new Date(dateStr.replace(" ", "T")).getTime();
}
var tasks = tasksBase.map((t) => {
  const related = submissions.filter((s) => s.taskId === t.id);
  const candidates = [t.createdAt, ...related.map((s) => s.submittedAt), ...related.flatMap((s) => s.decidedAt ? [s.decidedAt] : [])];
  const updatedAt = candidates.reduce((latest, ts) => toTimestamp(ts) > toTimestamp(latest) ? ts : latest, t.createdAt);
  return { ...t, updatedAt };
});
function buildInitialEvents(t, submission) {
  const events = [
    { id: `${t.id}-E1`, taskId: t.id, timestamp: t.createdAt, message: `Task created by ${t.createdBy}` }
  ];
  if (t.assignee) {
    events.push({ id: `${t.id}-E2`, taskId: t.id, timestamp: t.createdAt, message: `Assigned to ${t.assignee}` });
  }
  if (t.status === "accepted" || t.status === "in_progress" || t.status === "submitted" || t.status === "approved" || t.status === "rejected") {
    events.push({ id: `${t.id}-E3`, taskId: t.id, timestamp: t.createdAt, message: `${t.assignee} accepted the task` });
  }
  if (t.status === "declined") {
    events.push({ id: `${t.id}-E3`, taskId: t.id, timestamp: t.updatedAt, message: `${t.assignee} declined the task` });
  }
  if (t.status === "in_progress" || t.status === "submitted" || t.status === "approved" || t.status === "rejected") {
    events.push({ id: `${t.id}-E4`, taskId: t.id, timestamp: t.createdAt, message: `${t.assignee} started work` });
  }
  if (submission) {
    events.push({ id: `${t.id}-E5`, taskId: t.id, timestamp: submission.submittedAt, message: `${t.assignee} submitted proof of work` });
    if (submission.status === "approved") {
      events.push({ id: `${t.id}-E6`, taskId: t.id, timestamp: submission.decidedAt ?? submission.submittedAt, message: "Submission approved" });
    } else if (submission.status === "rejected") {
      events.push({ id: `${t.id}-E6`, taskId: t.id, timestamp: submission.decidedAt ?? submission.submittedAt, message: "Submission rejected \u2014 resubmission requested" });
    }
  }
  if (t.status === "canceled") {
    events.push({ id: `${t.id}-E7`, taskId: t.id, timestamp: t.updatedAt, message: "Task canceled by operator" });
  }
  return events.sort((a, b) => toTimestamp(a.timestamp) - toTimestamp(b.timestamp));
}
var initialTaskEvents = tasks.flatMap(
  (t) => buildInitialEvents(t, submissions.find((s) => s.taskId === t.id))
);
var CLOSED_STATUSES = ["approved", "rejected", "declined", "canceled"];
var OPEN_PIPELINE_STATUSES = ["open", "assigned", "accepted", "in_progress", "submitted"];
var ACCEPTED_OR_LATER_STATUSES = ["accepted", "in_progress", "submitted", "approved", "rejected"];
function isTaskOverdue(t) {
  return OPEN_PIPELINE_STATUSES.includes(t.status) && toTimestamp(t.dueAt) < toTimestamp(NOW);
}
function computeOpenTasksCount(tasksList = tasks) {
  return tasksList.filter((t) => !CLOSED_STATUSES.includes(t.status)).length;
}
function computeAwaitingReviewCount(tasksList = tasks) {
  return tasksList.filter((t) => t.status === "submitted").length;
}
function computeApprovedTasksCount(tasksList = tasks) {
  return tasksList.filter((t) => t.status === "approved").length;
}
function computeCollectorCounts(collectorsList = collectors) {
  return {
    total: collectorsList.length,
    active: collectorsList.filter((c) => c.status === "active").length,
    pending: collectorsList.filter((c) => c.status === "pending").length,
    inactiveOrSuspended: collectorsList.filter((c) => c.status === "inactive" || c.status === "suspended").length
  };
}
function computeCompletionRate(tasksList = tasks) {
  const assignedOrLater = tasksList.filter((t) => t.status !== "open" && t.status !== "canceled");
  const reachedReview = tasksList.filter((t) => t.status === "submitted" || t.status === "approved" || t.status === "rejected");
  return assignedOrLater.length ? Math.round(reachedReview.length / assignedOrLater.length * 100) : 0;
}
function computeAcceptanceRate(tasksList = tasks) {
  const acceptedOrLater = tasksList.filter((t) => ACCEPTED_OR_LATER_STATUSES.includes(t.status)).length;
  const declined = tasksList.filter((t) => t.status === "declined").length;
  return acceptedOrLater + declined ? Math.round(acceptedOrLater / (acceptedOrLater + declined) * 100) : 0;
}
function computeEstimatedWasteCollectedKg(submissionsList = submissions) {
  return submissionsList.filter((s) => s.status === "approved").reduce((sum, s) => sum + s.quantityKg, 0);
}
function computeOverdueTasksCount(tasksList = tasks) {
  return tasksList.filter(isTaskOverdue).length;
}
var last7Days = Array.from({ length: 7 }, (_, i) => {
  const d = new Date(toTimestamp(NOW) - (6 - i) * 864e5);
  return d.toISOString().slice(0, 10);
});
var statusOrder = ["open", "assigned", "accepted", "in_progress", "submitted", "approved", "declined", "rejected", "canceled"];
var statusDisplayLabel = {
  open: "Draft",
  assigned: "Assigned",
  accepted: "Accepted",
  in_progress: "In Progress",
  submitted: "Submitted",
  approved: "Approved",
  declined: "Declined",
  rejected: "Rejected",
  canceled: "Canceled"
};
function computeTaskStatusBreakdown(tasksList = tasks) {
  return statusOrder.map((status) => ({
    status,
    label: statusDisplayLabel[status],
    count: tasksList.filter((t) => t.status === status).length
  }));
}
function computeSubmissionCounts(submissionsList = submissions) {
  return {
    pending: submissionsList.filter((s) => s.status === "pending").length,
    approved: submissionsList.filter((s) => s.status === "approved").length,
    rejected: submissionsList.filter((s) => s.status === "rejected").length
  };
}
function computeAverageReviewMinutes(submissionsList = submissions) {
  const decided = submissionsList.filter((s) => s.decidedAt);
  if (!decided.length) return 0;
  const totalMinutes = decided.reduce((sum, s) => sum + (toTimestamp(s.decidedAt) - toTimestamp(s.submittedAt)) / 6e4, 0);
  return Math.round(totalMinutes / decided.length);
}
var taskIdCounter = Math.max(...tasks.map((t) => Number(t.id.split("-")[1]))) + 1;
var collectorIdCounter = Math.max(...collectors.map((c) => Number(c.id.split("-")[1]))) + 1;

// src/lib/mcp/tools/list-collectors.ts
var list_collectors_default = defineTool({
  name: "list_collectors",
  title: "List collectors",
  description: "List collectors in the Polis Systems demo dataset (name, phone, zone, status, type, organisation). Optionally filter by zone or status.",
  inputSchema: {
    zone: z.enum(ZONES).optional().describe("Filter to one operational zone."),
    status: z.enum(COLLECTOR_STATUSES).optional().describe("Filter by account status."),
    limit: z.number().int().min(1).max(200).optional().describe("Maximum number of collectors to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ zone, status, limit }) => {
    const filtered = collectors.filter(
      (c) => (!zone || c.zone === zone) && (!status || c.status === status)
    );
    const items = filtered.slice(0, limit ?? 50).map((c) => ({
      id: c.id,
      name: c.name,
      phone: c.phone,
      zone: c.zone,
      status: c.status,
      collectorType: c.collectorType,
      organization: c.organization,
      preferredLanguage: c.preferredLanguage,
      registeredAt: c.registeredAt,
      lastActiveAt: c.lastActiveAt
    }));
    const counts = computeCollectorCounts();
    return {
      content: [
        {
          type: "text",
          text: `Returning ${items.length} of ${filtered.length} matching collectors (dataset total: ${counts.total}).`
        }
      ],
      structuredContent: { counts, items }
    };
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod";
var TASK_STATUSES = [
  "open",
  "assigned",
  "accepted",
  "in_progress",
  "submitted",
  "approved",
  "declined",
  "rejected",
  "canceled"
];
var list_tasks_default = defineTool2({
  name: "list_tasks",
  title: "List sanitation tasks",
  description: "List cleanup tasks in the Polis Systems demo dataset. Optionally filter by zone, status, or priority.",
  inputSchema: {
    zone: z2.enum(ZONES).optional(),
    status: z2.enum(TASK_STATUSES).optional(),
    priority: z2.enum(PRIORITIES).optional(),
    limit: z2.number().int().min(1).max(200).optional().describe("Default 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ zone, status, priority, limit }) => {
    const filtered = tasks.filter(
      (t) => (!zone || t.zone === zone) && (!status || t.status === status) && (!priority || t.priority === priority)
    );
    const items = filtered.slice(0, limit ?? 50).map((t) => ({
      id: t.id,
      title: t.title,
      location: t.location,
      zone: t.zone,
      status: t.status,
      priority: t.priority,
      hotspotType: t.hotspotType,
      wasteType: t.wasteType,
      estimatedWasteKg: t.estimatedWasteKg,
      assignee: t.assignee,
      dueAt: t.dueAt,
      createdAt: t.createdAt
    }));
    return {
      content: [
        {
          type: "text",
          text: `Returning ${items.length} of ${filtered.length} matching tasks (dataset total: ${tasks.length}).`
        }
      ],
      structuredContent: { total: tasks.length, matched: filtered.length, items }
    };
  }
});

// src/lib/mcp/tools/operations-summary.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
var operations_summary_default = defineTool3({
  name: "get_operations_summary",
  title: "Operations summary",
  description: "Return top-level Polis Systems operational KPIs from the demo dataset: task counts by status, collector counts, waste collected, completion/acceptance rates, and submission review stats.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const summary = {
      tasks: {
        open: computeOpenTasksCount(),
        awaitingReview: computeAwaitingReviewCount(),
        approved: computeApprovedTasksCount(),
        overdue: computeOverdueTasksCount(),
        statusBreakdown: computeTaskStatusBreakdown()
      },
      collectors: computeCollectorCounts(),
      submissions: {
        counts: computeSubmissionCounts(),
        averageReviewMinutes: computeAverageReviewMinutes()
      },
      rates: {
        completionRatePct: computeCompletionRate(),
        acceptanceRatePct: computeAcceptanceRate()
      },
      estimatedWasteCollectedKg: computeEstimatedWasteCollectedKg()
    };
    return {
      content: [
        {
          type: "text",
          text: `Open ${summary.tasks.open} \xB7 Awaiting review ${summary.tasks.awaitingReview} \xB7 Approved ${summary.tasks.approved} \xB7 Active collectors ${summary.collectors.active}/${summary.collectors.total}.`
        }
      ],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "polis-systems-mcp",
  title: "Polis Systems MCP",
  version: "0.1.0",
  instructions: "Read-only tools that expose the Polis Systems sanitation operations demo dataset (Bengaluru pilot): collectors, cleanup tasks, and top-level operational KPIs. Use `get_operations_summary` first for an overview, then `list_tasks` or `list_collectors` to drill in with optional zone/status/priority filters.",
  tools: [operations_summary_default, list_tasks_default, list_collectors_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
